### ISSUE TITLE
Create Guild Leaderboards

### ISSUE THREAD

**Issue by heftymouse** [BoogieMonster1O1/EyeYouReadyForIt#10]
Pretty self explanatory. There are a couple of things that need to be worked out though, like:

- How and when to give and take points from users
- How and where to store guild data
- The potential privacy and security implications of this

In addition, this requires a way to permanently host the bot (#9)

**Comment by heftymouse** [comment]
It's now pretty much entirely done, #15

**Comment by heftymouse** [comment]
PagMan

**Comment by heftymouse** [comment]
Now all that remains is to create a privacy policy

**Comment by BoogieMonster1O1** [comment]
oh
ok
i wil do

**Comment by heftymouse** [comment]
okie

**Comment by heftymouse** [comment]
just for reference to make your life easier, the data we store is the correct answers, wrong answers, hints used and games won for each user in each guild
along with the total tourneys played and the number of missed eyes
add an invite to the discord in case a server owner wants their data deleted or smth

**Comment by BoogieMonster1O1** [comment]
got it

**Comment by heftymouse** [comment]
extremely epic

**Comment by heftymouse** [comment]
We're done people
